print("welcome to the tip calculator")
user_bill = input("how much was the total bill?: ")
tip = input("how much tip would you like to give: 10, 12, or 15? ")
num_people = input("how many to split the bill?: ")
print("Each person should pay: " + round(((float(user_bill) * (float(tip)/100))/num_people), 2))
